export {
    HYPERBOLIC_REGULAR_NGON_DEFAULT_N,
    HYPERBOLIC_REGULAR_NGON_DEFAULT_Q,
    HYPERBOLIC_REGULAR_NGON_N_MAX,
    HYPERBOLIC_REGULAR_NGON_N_MIN,
    HYPERBOLIC_REGULAR_NGON_Q_MAX,
    HYPERBOLIC_REGULAR_NGON_Q_MIN,
    HYPERBOLIC_REGULAR_NGON_ROTATION,
    HYPERBOLIC_REGULAR_NGON_SCENE_ID,
    HYPERBOLIC_REGULAR_NGON_SCENE_KEY,
} from "./constants";

export { hyperbolicRegularNgonScene } from "./definition";
