export const HYPERBOLIC_TILING_TRIPLE_FAMILY_MIN_R = 3;
export const HYPERBOLIC_TILING_TRIPLE_FAMILY_MAX_R = 30;
export const HYPERBOLIC_TILING_TRIPLE_FAMILY_STEP = 0.1;
export const HYPERBOLIC_TILING_TRIPLE_FAMILY_REFLECTIONS = 100;
